Tests and work on ONH detection, and minor improvements on a few functions
DCC-Lab/ZiliaImageAligningProject pull request #9
Opened 2021-06-02 20:49 UTC by emilemarcotte

2021-06-08 18:56 UTC, dccote requested changes

2021-06-08 18:56 UTC, dccote commented on tests/testsOtsuThreshold.py
> +        self.assertTrue(type(thresh) == np.int32)
This test fails because it is np.int64 on my machine.  Is it important for it to be int32? Whay are you testing this?

2021-06-08 19:08 UTC, emilemarcotte commented on tests/testsOtsuThreshold.py
> +        self.assertTrue(type(thresh) == np.int32)
I was testing this simply to check that the output threshold is only a number, not some kind of array. If it doesn't give the same type of number on every computer, should we just skip the test and leave a comment saying "the output is confirmed to be a single number" or something like that?

2021-06-08 19:16 UTC, emilemarcotte commented on tests/testsOtsuThreshold.py
> +        self.assertTrue(type(thresh) == np.int32)
I just skipped the 2 threshold type tests. It doesn't really matter in practice if they are ints or floats, the only thing that matters in that context is that they are just number.

2021-06-10 14:54 UTC, dccote approved these changes

2021-06-10 14:54 UTC, merged